{
  "hash": "c5398c332031565e5426e268cc46a3f9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'AE 10: Modelling fish'\nsubtitle: Suggested answers\ncategories:\n  - Application exercise\n  - Answers\nfig-width: 7\nfig-asp: 0.618\nexecute:\n  warning: false\n  error: false\n---\n\n::: callout-important\nThese are suggested answers.\nThis document should be used as reference only, it's not designed to be an exhaustive key.\n:::\n\nFor this application exercise, we will work with data on fish.\nThe dataset we will use, called `fish`, is on two common fish species in fish market sales.\n\n::: {#load-packages-data .cell message='false' execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nfrom sklearn.linear_model import LinearRegression\nimport numpy as np\n\nfish = pd.read_csv(\"data/fish.csv\")\nprint(fish.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  species  weight  length_vertical  length_diagonal  length_cross   height  \\\n0   Bream     242             23.2             25.4          30.0  11.5200   \n1   Bream     290             24.0             26.3          31.2  12.4800   \n2   Bream     340             23.9             26.5          31.1  12.3778   \n3   Bream     363             26.3             29.0          33.5  12.7300   \n4   Bream     430             26.5             29.0          34.0  12.4440   \n\n    width  \n0  4.0200  \n1  4.3056  \n2  4.6961  \n3  4.4555  \n4  5.1340  \n```\n:::\n:::\n\n\nThe data dictionary is below:\n\n| **variable**      | **description**        |\n|-------------------|------------------------|\n| `species`         | Species name of fish   |\n| `weight`          | Weight, in grams       |\n| `length_vertical` | Vertical length, in cm |\n| `length_diagonal` | Diagonal length, in cm |\n| `length_cross`    | Cross length, in cm    |\n| `height`          | Height, in cm          |\n| `width`           | Diagonal width, in cm  |\n\n# Visualizing the model\n\nWe're going to investigate the relationship between the weights and heights of fish.\n\n-   Create an appropriate plot to investigate this relationship. Add appropriate labels to the plot.\n\n::: {#cell-plot-hw .cell execution_count=2}\n``` {.python .cell-code}\nplt.figure(figsize=(8, 6))\nsns.scatterplot(x='height', y='weight', data=fish, alpha=0.5)\nplt.xlabel(\"Height (cm)\")\nplt.ylabel(\"Weight (g)\")\nplt.title(\"Relationship between Heights and Weights of Fish\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ae-10-modeling-fish-A_files/figure-html/plot-hw-output-1.png){#plot-hw width=676 height=523}\n:::\n:::\n\n\n-   If you were to draw a a straight line to best represent the relationship between the heights and weights of fish, where would it go?\n    Why?\n\n    *Start from the bottom and go up Identify the first and last point and draw a line through most the others.*\n\n    -   Now, let Python draw the line for you. Refer to the documentation at <https://seaborn.pydata.org/generated/seaborn.lmplot.html>. Specifically, refer to the `method` section.\n\n\n    ::: {#cell-plot-hw-lm .cell execution_count=3}\n    ``` {.python .cell-code}\n    # Fit a linear model\n    X = fish[['height']]\n    y = fish['weight']\n    model = LinearRegression()\n    model.fit(X, y)\n    \n    # Predict values\n    predictions = model.predict(X)\n    \n    plt.figure(figsize=(8, 6))\n    sns.scatterplot(x='height', y='weight', data=fish, alpha=0.5)\n    plt.plot(fish['height'], predictions, color=\"#325b74\", linewidth=2)\n    plt.xlabel(\"Height (cm)\")\n    plt.ylabel(\"Weight (g)\")\n    plt.title(\"Relationship between Heights and Weights of Fish with Linear Regression Line\")\n    plt.show()\n    ```\n    \n    ::: {.cell-output .cell-output-display}\n    ![](ae-10-modeling-fish-A_files/figure-html/plot-hw-lm-output-1.png){#plot-hw-lm width=690 height=523}\n    :::\n    :::\n    \n    \n    -   What types of questions can this plot help answer?\n\n        *Is there a relationship between fish heights and weights of fish?*\n\n    We can use this line to make predictions.\n    Predict what you think the weight of a fish would be with a height of 10 cm, 15 cm, and 20 cm.\n    Which prediction is considered extrapolation?\n\n    -   *At 10 cm, we estimate a weight of 375 grams. At 15 cm, we estimate a weight of 600 grams At 20 cm, we estimate a weight of 975 grams. 20 cm would be considered extrapolation.*\n\n    -   What is a residual?\n\n        *Difference between predicted and observed.*\n\n# Model fitting\n\n-   Fit a model to predict fish weights from their heights.\n\n::: {#fit-model .cell execution_count=4}\n``` {.python .cell-code}\nmodel = LinearRegression()\nmodel.fit(X, y)\n\nfish['predicted_weight'] = model.predict(X)\nfish['residual'] = fish['weight'] - fish['predicted_weight']\n```\n:::\n\n\n-   Predict what the weight of a fish would be with a height of 10 cm, 15 cm, and 20 cm using this model.\n\n::: {#predict-by-hand .cell execution_count=5}\n``` {.python .cell-code}\nheights = np.array([[10], [15], [20]])\npredicted_weights = model.predict(heights)\nfor height, weight in zip(heights, predicted_weights):\n    print(f\"Predicted weight for height {height[0]} cm: {weight:.2f} g\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPredicted weight for height 10 cm: 320.74 g\nPredicted weight for height 15 cm: 625.32 g\nPredicted weight for height 20 cm: 929.90 g\n```\n:::\n:::\n\n\n-   Calculate predicted weights for all fish in the data and visualize the residuals under this model.\n\n::: {#cell-residuals .cell execution_count=6}\n``` {.python .cell-code}\nfish['predicted_weight'] = model.predict(X)\nfish['residual'] = fish['weight'] - fish['predicted_weight']\n\nplt.figure(figsize=(8, 6))\nsns.scatterplot(x='height', y='residual', data=fish, alpha=0.5)\nplt.axhline(0, color='red', linestyle='--')\nplt.xlabel(\"Height (cm)\")\nplt.ylabel(\"Residual (g)\")\nplt.title(\"Residuals of the Linear Regression Model\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ae-10-modeling-fish-A_files/figure-html/residuals-output-1.png){#residuals width=679 height=523}\n:::\n:::\n\n\n# Model summary\n\n-   Display the model summary including estimates for the slope and intercept along with measurements of uncertainty around them. Show how you can extract these values from the model output.\n\n::: {#model-summary .cell execution_count=7}\n``` {.python .cell-code}\nslope = model.coef_[0]\nintercept = model.intercept_\nprint(f\"Slope: {slope:.2f}\")\nprint(f\"Intercept: {intercept:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSlope: 60.92\nIntercept: -288.42\n```\n:::\n:::\n\n\n-   Write out your model using mathematical notation.\n\n$\\widehat{weight} = -288 + 60.9 \\times height$\n\n# Correlation\n\nWe can also assess correlation between two quantitative variables.\n\n-   What is correlation? What are values correlation can take?\n    -   *Strength and direction of a linear relationship. It's bounded by -1 and 1.*\n\n    -   Are you good at guessing correlation?\n        Give it a try!\n        <https://www.rossmanchance.com/applets/2021/guesscorrelation/GuessCorrelation.html>\n-   What is the correlation between heights and weights of fish?\n\n::: {#b0c8b73d .cell execution_count=8}\n``` {.python .cell-code}\ncorrelation = fish['height'].corr(fish['weight'])\nprint(f\"Correlation between height and weight: {correlation:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCorrelation between height and weight: 0.95\n```\n:::\n:::\n\n\n# Adding a third variable\n\n-   Does the relationship between heights and weights of fish change if we take into consideration species? Plot two separate straight lines for the Bream and Roach species.\n\n::: {#plot-hws-lm .cell execution_count=9}\n``` {.python .cell-code}\nplt.figure(figsize=(8, 6))\nsns.lmplot(x='height', y='weight', hue='species', data=fish, markers=[\"o\", \"s\"], ci=None, palette=\"muted\", height=6, aspect=1.5)\nplt.xlabel(\"Height (cm)\")\nplt.ylabel(\"Weight (g)\")\nplt.title(\"Relationship between Heights and Weights of Fish by Species\")\nplt.show()\n```\n\n::: {#plot-hws-lm-1 .cell-output .cell-output-display}\n```\n<Figure size 768x576 with 0 Axes>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ae-10-modeling-fish-A_files/figure-html/plot-hws-lm-output-2.png){#plot-hws-lm-2 width=946 height=586}\n:::\n:::\n\n\n# Fitting other models\n\n-   We can fit more models than just a straight line. Change the `sns.regplot()` code you previously used to include `lowess=True`. What is different from the plot created before?\n\n::: {#cell-plot-hw-loess .cell execution_count=10}\n``` {.python .cell-code}\nplt.figure(figsize=(8, 6))\nsns.scatterplot(x='height', y='weight', data=fish, alpha=0.5)\nsns.regplot(x='height', y='weight', data=fish, lowess=True, scatter_kws={'s':10}, line_kws={'color':'red'})\nplt.xlabel(\"Height (cm)\")\nplt.ylabel(\"Weight (g)\")\nplt.title(\"Relationship between Heights and Weights of Fish with LOESS Smoothing\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ae-10-modeling-fish-A_files/figure-html/plot-hw-loess-output-1.png){#plot-hw-loess width=676 height=523}\n:::\n:::\n\n\n",
    "supporting": [
      "ae-10-modeling-fish-A_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}