{
  "hash": "3f55cc5361a19b165e9b41216a1224fb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Exam 2 Review\nformat:\n  html: default\n  pdf: default\nexecute:\n  echo: false\n  message: false\n  error: false\n  warning: false\neditor_options:\n  chunk_output_type: console\n---\n\n\n\n::: callout-note\nSuggested answers can be found [here](/exam-review/exam-2-review-A.qmd), but resist the urge to peek before you go through it yourself.\n:::\n\n# Part 1 - Employment\n\nA large university knows that about 70% of the full-time students are employed at least 5 hours per week.\nThe members of the Statistics Department wonder if the same proportion of their students work at least 5 hours per week.\nThey randomly sample 25 majors and find that 15 of the students (60%) work 5 or more hours each week.\n\n## Question 1\n\nDescribe how you can set up a simulation to estimate the proportion of statistics majors who work 5 or more hours each week based on this sample.\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n## Question 2\n\nA bootstrap distribution with 1000 simulations is shown below.\nApproximate the bounds of the 95% confidence interval based on this distribution.\n\n\n\n![](images/sim-bootstrap.png){width=\"667\"}\n\n## Question 3\n\nSuppose the lower bound of the confidence interval from the previous question is L and the upper bound is U.\nWhich of the following is correct?\n\na\\.\nBetween L to U of statistics majors work at least 5 hours per week.\n\nb\\.\n95% of the time the true proportion of statistics majors who work at least 5 hours per week is between L and U.\n\nc\\.\nBetween L and U of random samples of 25 statistics majors are expected to yield confidence intervals that contain the true proportion of statistics majors who work at least 5 hours per week.\n\nd\\.\n95% of random samples of 25 statistics majors will yield confidence intervals between L and U.\n\ne\\.\nNone of the above.\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n# Part 2 - Blizzard\n\n\n\nIn 2020, employees of Blizzard Entertainment circulated a spreadsheet to anonymously share salaries and recent pay increases amidst rising tension in the video game industry over wage disparities and executive compensation.\n(Source: [Blizzard Workers Share Salaries in Revolt Over Pay](https://www.bloomberg.com/news/articles/2020-08-03/blizzard-workers-share-salaries-in-revolt-over-wage-disparities))\n\nThe name of the data frame used for this analysis is `blizzard_salary` and the variables are:\n\n-   `percent_incr`: Raise given in July 2020, as percent increase with values ranging from 1 (1% increase to 21.5 (21.5% increase)\n\n-   `salary_type`: Type of salary, with levels `Hourly` and `Salaried`\n\n-   `annual_salary`: Annual salary, in USD, with values ranging from \\$50,939 to \\$216,856.\n\n-   `performance_rating`: Most recent review performance rating, with levels `Poor`, `Successful`, `High`, and `Top`.\n    The `Poor` level is the lowest rating and the `Top` level is the highest rating.\n\nThe top ten rows of `blizzard_salary` are shown below:\n\n::: {#9563dbce .cell execution_count=4}\n\n::: {.cell-output .cell-output-stdout}\n```\n   percent_incr salary_type  annual_salary performance_rating\n0           1.0        year            1.0               High\n1           1.0        year            1.0         Successful\n2           1.0        year            1.0               High\n3           1.0      Hourly        33987.2         Successful\n4           NaN      Hourly        34798.4               High\n5           NaN      Hourly        35360.0                NaN\n6           NaN      Hourly        37440.0                NaN\n7           0.0      Hourly        37814.4                NaN\n8           4.0      Hourly        41100.8                Top\n9           1.2      Hourly        42328.0                NaN\n```\n:::\n:::\n\n\n## Question 4\n\nNext, you fit a model for predicting raises (`percent_incr`) from salaries (`annual_salary`).\nWe'll call this model `raise_1_fit`.\nAn output of the model is shown below.\n\n::: {#raise-salary-fit .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\n                  Coef.  Std.Err.         t     P>|t|    [0.025    0.975]\nIntercept      1.869965  0.432035  4.328268  0.000019  1.020397  2.719532\nannual_salary  0.000016  0.000005  3.431459  0.000669  0.000007  0.000024\n```\n:::\n:::\n\n\nWhich of the following is the best interpretation of the slope coefficient?\n\na.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 1.6%.\nb.  For every additional \\$1,000 of annual salary, the raise goes up by 0.016%.\nc.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 0.016%.\nd.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 1.87%.\n\n## Question 5\n\nYou then fit a model for predicting raises (`percent_incr`) from salaries (`annual_salary`) and performance ratings (`performance_rating`).\nWe'll call this model `raise_2_fit`.\nWhich of the following is definitely true based on the information you have so far?\n\na.  Intercept of `raise_2_fit` is higher than intercept of `raise_1_fit`.\nb.  Slope of `raise_2_fit` is higher than RMSE of `raise_1_fit`.\nc.  Adjusted $R^2$ of `raise_2_fit` is higher than adjusted $R^2$ of `raise_1_fit`.\nd.  $R^2$ of `raise_2_fit` is higher $R^2$ of `raise_1_fit`.\n\n## Question 6\n\nThe tidy model output for the `raise_2_fit` model you fit is shown below.\n\n::: {#raise-salary-rating-fit .cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n```\n                                          Coef.  Std.Err.         t  \\\nIntercept                              2.617865  0.452366  5.787046   \nperformance_rating_Poor[T.True]       -3.499070  1.500230 -2.332356   \nperformance_rating_Successful[T.True] -1.730554  0.361704 -4.784449   \nperformance_rating_Top[T.True]         3.628454  0.730187  4.969215   \nannual_salary                          0.000013  0.000004  3.119855   \n\n                                              P>|t|    [0.025    0.975]  \nIntercept                              1.543384e-08  1.728293  3.507437  \nperformance_rating_Poor[T.True]        2.022505e-02 -6.449249 -0.548892  \nperformance_rating_Successful[T.True]  2.493372e-06 -2.441838 -1.019269  \nperformance_rating_Top[T.True]         1.035401e-06  2.192554  5.064355  \nannual_salary                          1.953363e-03  0.000005  0.000021  \n```\n:::\n:::\n\n\nWhen your teammate sees this model output, they remark \"The coefficient for `performance_ratingSuccessful` is negative, that's weird. I guess it means that people who get successful performance ratings get lower raises.\" How would you respond to your teammate?\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n## Question 7\n\nUltimately, your teammate decides they don't like the negative slope coefficients in the model output you created (not that there's anything wrong with negative slope coefficients!), does something else, and comes up with the following model output.\n*Note however that the coefficient is still negative, but this satisfies your friend...*\n\n::: {#b839c991 .cell execution_count=7}\n\n::: {.cell-output .cell-output-stdout}\n```\n                                          Coef.  Std.Err.         t  \\\nIntercept                              1.785333  0.509233  3.505927   \nperformance_rating_Successful[T.True] -0.800356  0.439216 -1.822238   \nperformance_rating_High[T.True]        1.574196  0.475552  3.310248   \nperformance_rating_Top[T.True]         4.569528  0.768132  5.948886   \nannual_salary                          0.000012  0.000004  2.854297   \n\n                                              P>|t|    [0.025    0.975]  \nIntercept                              5.116857e-04  0.783935  2.786732  \nperformance_rating_Successful[T.True]  6.923704e-02 -1.664068  0.063355  \nperformance_rating_High[T.True]        1.025064e-03  0.639030  2.509362  \nperformance_rating_Top[T.True]         6.327904e-09  3.059009  6.080047  \nannual_salary                          4.559386e-03  0.000004  0.000020  \n```\n:::\n:::\n\n\nUnfortunately they didn't write their code in a Quarto document, instead just wrote some code in the Console and then lost track of their work.\nThey remember using the `fct_relevel()` function and doing something like the following:\n\n::: {#38ba213b .cell execution_count=8}\n``` {.python .cell-code}\nblizzard_salary['performance_rating'] = pd.Categorical(\n    blizzard_salary['performance_rating'],\n    categories=[____],\n    ordered=True\n)\n```\n:::\n\n\nWhat should they put in the blanks to get the same model output as above?\n\na.  \"Poor\", \"Successful\", \"High\", \"Top\"\nb.  \"Successful\", \"High\", \"Top\"\nc.  \"Top\", \"High\", \"Successful\", \"Poor\"\nd.  Poor, Successful, High, Top\n\n## Question 8\n\nSuppose we fit a model to predict `percent_incr` from `annual_salary` and `salary_type`.\nA tidy output of the model is shown below.\n\n::: {#raise-salary-type-fit .cell execution_count=9}\n\n::: {.cell-output .cell-output-stdout}\n```\n                             Coef.  Std.Err.         t     P>|t|    [0.025  \\\nIntercept                 1.242597  0.570278  2.178932  0.029972  0.121174   \nsalary_type_year[T.True]  0.913343  0.543715  1.679819  0.093844 -0.155845   \nannual_salary             0.000014  0.000005  2.958979  0.003287  0.000005   \n\n                            0.975]  \nIntercept                 2.364020  \nsalary_type_year[T.True]  1.982532  \nannual_salary             0.000023  \n```\n:::\n:::\n\n\nWhich of the following visualizations represent this model?\nExplain your reasoning.\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {#cell-fig-raise-salary-type .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![](final-review_files/figure-html/fig-raise-salary-type-output-1.png){#fig-raise-salary-type}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {#cell-fig-raise-salary-type-2 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![](final-review_files/figure-html/fig-raise-salary-type-2-output-1.png){#fig-raise-salary-type-2}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n:::\n\n\n:::\n:::\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {#cell-fig-raise-salary-type-3 .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![](final-review_files/figure-html/fig-raise-salary-type-3-output-1.png){#fig-raise-salary-type-3}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {#cell-fig-raise-salary-type-4 .cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![](final-review_files/figure-html/fig-raise-salary-type-4-output-1.png){#fig-raise-salary-type-4}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n:::\n\n\n:::\n:::\n\nVisualizations of the relationship between percent increase, annual salary, and salary type\n\na.  Figure 1\nb.  Figure 2\nc.  Figure 3\nd.  Figure 4\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n{{< pagebreak >}}\n\n\n\n\n:::\n\n## Question 9\n\nDefine the term parsimonious model.\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n## Question 10\n\nSuppose you now fit a model to predict the natural log of percent increase, `log(percent_incr)`, from performance rating.\nThe model is called `raise_4_fit`.\n\n\n\nYou're provided the following:\n\n::: {#47fee572 .cell execution_count=15}\n``` {.python .cell-code}\nraise_4_fit_coefs['exp_estimate'] = np.exp(raise_4_fit_coefs['estimate'])\nprint(raise_4_fit_coefs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            term  estimate  exp_estimate\n0                      Intercept -2.088594      0.123861\n1  performance_rating_Successful  1.872176      6.502427\n2        performance_rating_High  3.110229     22.426176\n3         performance_rating_Top  3.854360     47.198390\n```\n:::\n:::\n\n\nBased on this, which of the following is true?\n\na\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by 10.25% compared to the employees with Poor performance rating.\n\nb\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by 6.93% compared to the employees with Poor performance rating.\n\nc\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 6.502427 compared to the employees with Poor performance rating.\n\nd\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 1.872176 compared to the employees with Poor performance rating.\n\n## Question 11\n\nWhich of the following is the definiton of a regression model?\nSelect all that apply.\n\na\\.\n$\\hat{y} = \\beta_0 + \\beta_1 X_1$\n\nb\\.\n$y = \\beta_0 + \\beta_1 X_1$\n\nc\\.\n$\\hat{y} = \\beta_0 + \\beta_1 X_1 + \\epsilon$\n\nd\\.\n$y = \\beta_0 + \\beta_1 X_1 + \\epsilon$\n\n# Part 3 - Calculus\n\n## Question 12\n\nCompute the derivative $( \\frac{d}{dx} )$ of the following function:\n\n$$\ng(x) = \\left( \\sin(x^2) + \\cos(ax) \\right)^k\n$$\n\n## Question 13\n\nCompute the following integral:\n\n$$\n\\int_{a}^{b} \\left( e^{cx} + \\frac{1}{x^n} \\right) dx\n$$\n\n# Part 4 - Linear algebra\n\n## Question 14\n\nGiven a vector $x = \\begin{bmatrix} x_1 \\\\ x_2 \\\\ x_3 \\\\ x_4 \\end{bmatrix}$, write down its transpose $x^\\top$.\n\n## Question 15\n\nGiven the following matrix $N$:\n\n$$\nN = \\begin{bmatrix}\nn_{11} & n_{12} \\\\\nn_{21} & n_{22} \\\\\nn_{31} & n_{32} \\\\\nn_{41} & n_{42}\n\\end{bmatrix}\n$$\n\nWrite down its transpose, $N^\\top$.\n\n## Question 16\n\nConsider the following matrices $C$ and $D$:\n\n$$\nC = \n\\begin{bmatrix}c_{11} & c_{12} \\\\c_{21} & c_{22} \\\\c_{31} & c_{32}\\end{bmatrix}, \\quad\nD =\n\\begin{bmatrix}d_{11} & d_{12} & d_{13} \\\\d_{21} & d_{22} & d_{23}\\end{bmatrix}\n$$\n\n1.  What are the dimensions of $C$?\n2.  What are the dimensions of $D$?\n3.  For the matrix product $CD$:\n    1.  Determine if the product is valid, and explain why.\n    2.  If the product is valid, write down the dimensions of the resulting matrix without computing the product.\n\n## Question 17\n\nGiven the matrices $E$ and $F$:\n\n$$\nE = \\begin{bmatrix}\ne_{11} & e_{12} \\\\\ne_{21} & e_{22} \\\\\ne_{31} & e_{32}\n\\end{bmatrix}, \\quad\nF = \\begin{bmatrix}\nf_{11} \\\\\nf_{21}\n\\end{bmatrix}\n$$\n\n1.  What are the dimensions of $E$?\n2.  What are the dimensions of $F$?\n3.  For the matrix product $EF$:\n    1.  Determine if the product is valid, and explain why.\n    2.  If the product is valid, compute the resulting matrix.\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n## Bonus\n\nPick a concept we introduced in class so far that you've been struggling with and explain it in your own words.\n\n",
    "supporting": [
      "final-review_files"
    ],
    "filters": [],
    "includes": {}
  }
}