---
title: "AE 15: Linear algebra"
subtitle: "Suggested answers"
categories: 
  - Application exercise
  - Answers
---

In this exercise, we will:

-   Transpose a Vector: Learn how to transpose a given vector.
-   Transpose a Matrix: Understand the concept of matrix transposition by working with a given matrix.
-   Determine Matrix Dimensions: Identify and write down the dimensions of given matrices.
-   Matrix Multiplication Validity: Check the validity of matrix multiplication for given matrices and determine the dimensions of the resulting matrix if valid.
-   Compute Matrix Product: Perform the actual computation of a matrix product for given matrices when the multiplication is valid.

# Linear algebra

For each exercise, show all steps clearly.

## Transposition

### Exercise 1

Given a vector$\mathbf{y}$**:**

$$
\mathbf{y} = \begin{bmatrix} y_1 \\ y_2 \\ y_3 \end{bmatrix}
$$

Write down its transpose $\mathbf{y}^\top$

**Solution:**

-   The transpose of the vector $\mathbf{y}$ is:

$$
\mathbf{y}^\top = \begin{bmatrix} y_1 & y_2 & y_3 \end{bmatrix}
$$

### Exercise 2

Given the following matrix $\mathbf{N}$:

$$
\mathbf{N} = \begin{bmatrix}n_{11} & n_{12} \\n_{21} & n_{22} \\n_{31} & n_{32}\end{bmatrix}
$$

Write down its transpose, $\mathbf{N}^{\top}$

**Solution:**

-   The transpose of the matrix $\mathbf{N}$ is:

$$
\mathbf{N}^\top = \begin{bmatrix}n_{11} & n_{21} & n_{31} \\n_{12} & n_{22} & n_{32}\end{bmatrix}
$$

## Matrix operations

### Exercise 3

Consider the following matrices $\mathbf{C}$ and $\mathbf{D}$:

$$
\mathbf{C} = \begin{bmatrix}c_{11} & c_{12} & c_{13} \\c_{21} & c_{22} & c_{23}\end{bmatrix}, \quad\mathbf{D} = \begin{bmatrix}d_{11} & d_{12} \\d_{21} & d_{22} \\d_{31} & d_{32}\end{bmatrix}
$$

-   What are the dimensions of $\mathbf{C}$?

-   What are the dimensions of $\mathbf{D}$?

-   For the matrix product $\mathbf{C} \mathbf{D}$:

    1.  Determine if the product is valid, and explain why.

    2.  If the product is valid, write down the dimensions of the resulting matrix without computing the product.

**Solution:**

-   The dimensions of $\mathbf{C}$ are $2 \times 3$

-   The dimensions of $\mathbf{D}$ are $3 \times 2$.

-   For the matrix product $\mathbf{C} \mathbf{D}$:

    1.  The product is valid because the number of columns in $\mathbf{C}$ (which is 3) matches the number of rows in $\mathbf{D}$ (which is 3).

    2.  The dimensions of the resulting matrix will be $2 \times 2$.

### Exercise 4

Consider the following matrices $\mathbf{E}$ and $\mathbf{F}$:

$$
\mathbf{E} = \begin{bmatrix}e_{11} & e_{12} & e_{13} & e_{14} \\e_{21} & e_{22} & e_{23} & e_{24}\end{bmatrix}, \quad\mathbf{F} = \begin{bmatrix}f_{11} & f_{12} \\f_{21} & f_{22} \\f_{31} & f_{32} \\f_{41} & f_{42}\end{bmatrix}
$$

-   What are the dimensions of $\mathbf{E}$?

-   What are the dimensions of $\mathbf{F}$?

-   For the matrix product $\mathbf{E} \mathbf{F}$:

    1.  Determine if the product is valid, and explain why.

    2.  If the product is valid, write down the dimensions of the resulting matrix without computing the product.

**Solution:**

-   The dimensions of $\mathbf{F}$ are $2 \times 4$

-   The dimensions of $\mathbf{F}$ are $4 \times 2$.

-   For the matrix product $\mathbf{E} \mathbf{F}$:

    1.  The product is valid because the number of columns in $\mathbf{E}$ (which is 4) matches the number of rows in $\mathbf{F}$ (which is 4).

    2.  The resulting matrix is:

$$
\mathbf{E} \mathbf{F} = \begin{bmatrix}e_{11} & e_{12} & e_{13} & e_{14} \\e_{21} & e_{22} & e_{23} & e_{24}\end{bmatrix}\begin{bmatrix}f_{11} & f_{12} \\f_{21} & f_{22} \\f_{31} & f_{32} \\f_{41} & f_{42}\end{bmatrix}= \\\begin{bmatrix}e_{11}f_{11} + e_{12}f_{21} + e_{13}f_{31} + e_{14}f_{41} & e_{11}f_{12} + e_{12}f_{22} + e_{13}f_{32} + e_{14}f_{42} \\e_{21}f_{11} + e_{22}f_{21} + e_{23}f_{31} + e_{24}f_{41} & e_{21}f_{12} + e_{22}f_{22} + e_{23}f_{32} + e_{24}f_{42}\end{bmatrix}
$$
